pipeline:
  create_cluster:
    image: banzaicloud/ci-pipeline-client:0.12
    cluster:
      cloud: amazon
      location: eu-west-1
      name: c3z9c00rz30nl
      properties:
        pke:
          cri:
            runtime: containerd
          kubernetes:
            rbac:
              enabled: true
            version: 1.15.7
          nodepools:
          - autoscaling: true
            name: pool0
            provider: amazon
            providerConfig:
              autoScalingGroup:
                instanceType: t2.medium
                launchConfigurationName: pool0
                name: pool0
                size:
                  desired: 3
                  max: 4
                  min: 3
                spotPrice: ""
                zones:
                - eu-west-1a
            roles:
            - worker
          - autoscaling: false
            name: master
            provider: amazon
            providerConfig:
              autoScalingGroup:
                instanceType: c5.large
                launchConfigurationName: master
                name: master
                size:
                  desired: 1
                  max: 1
                  min: 1
                spotPrice: ""
                zones:
                - eu-west-1a
            roles:
            - master
      secretName: awsaccount
    action: EnsureCluster
  test:
    image: node:10-slim
    commands:
    - npm ci
    - npm test
  build_image:
    dockerfile: Dockerfile
    image: banzaicloud/kaniko-plugin
    repo: hiroshui/hiroshui-cloud
    secretFrom:
      DOCKER_PASSWORD:
        keyRef: password
        name: docker-hub
      DOCKER_USERNAME:
        keyRef: username
        name: docker-hub
    tags: '{{ trunc 7 .CICD_COMMIT_SHA }}'
  package_application:
    when:
      branch:
        include:
        - master
    image: lachlanevenson/k8s-helm:v2.16.1
    commands:
    - helm init -c
    - helm repo add stable https://kubernetes-charts.storage.googleapis.com
    - helm repo add banzaicloud-stable https://kubernetes-charts.banzaicloud.com
    - helm package ./.banzaicloud/charts/spotguide-nodejs-mongodb
  install_mongodb_user_secret:
    action: InstallSecret
    clusterSecret:
      merge: true
      name: '{{ .CICD_REPO_NAME }}-mongodb'
      namespace: default
      sourceSecretName: test-mongo-mongodb
      spec:
      - name: mongodb-username
        source: username
      - name: mongodb-password
        source: password
    image: banzaicloud/ci-pipeline-client:0.12
    when:
      branch:
        include:
        - master
  install_mongodb_root_secret:
    action: InstallSecret
    clusterSecret:
      merge: true
      name: '{{ .CICD_REPO_NAME }}-mongodb'
      namespace: default
      spec:
      - name: mongodb-root-password
        source: password
    image: banzaicloud/ci-pipeline-client:0.12
    when:
      branch:
        include:
        - master
  install_mongodb_replica_set_key_secret:
    action: InstallSecret
    clusterSecret:
      merge: true
      name: '{{ .CICD_REPO_NAME }}-mongodb'
      namespace: default
      sourceSecretName: test-mongo-mongodb-replicaset-key
      spec:
      - name: mongodb-replica-set-key
        source: password
    image: banzaicloud/ci-pipeline-client:0.12
    when:
      branch:
        include:
        - master
  deploy_application:
    action: EnsureDeployment
    deployment:
      name: ./spotguide-nodejs-mongodb-1.0.0.tgz
      namespace: default
      releaseName: '{{ .CICD_REPO_NAME }}'
      reuseValues: true
      timeout: 900
      values:
        deployment:
          image:
            pullPolicy: Always
            repository: hiroshui/hiroshui-cloud
            tag: '{{ trunc 7 .CICD_COMMIT_SHA }}'
        ingress:
          annotations:
            kubernetes.io/ingress.class: traefik
            traefik.ingress.kubernetes.io/redirect-permanent: "true"
            traefik.ingress.kubernetes.io/redirect-regex: ^http://(.*)
            traefik.ingress.kubernetes.io/redirect-replacement: https://$1
          hosts:
          - '{{ lower (printf "app-%s-%s.%s.%s" .CICD_REPO_NAME (.CLUSTER_NAME | sha1sum | trunc 10) .ORG_NAME .DOMAIN_NAME) }}'
        mongodb:
          existingSecret: '{{ .CICD_REPO_NAME }}-mongodb'
          metrics:
            enabled: true
          mongodbDatabase: node-application
          replicaSet:
            enabled: true
          usePassword: true
      wait: true
    image: banzaicloud/ci-pipeline-client:0.12
    when:
      branch:
        include:
        - master
